### Домашняя работа 2

1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [3]:
import numpy as np

array = np.ones((10, 10))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [10]:
array = np.indices((8, 8)).sum(axis=0) % 2
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [12]:
array = np.diag([1, 2, 3, 4], k=-1)
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [15]:
array = np.random.random((5, 5))
array_normalized = array - array.mean(axis=1, keepdims=True)
print(array_normalized)

[[-0.27383602 -0.14386372 -0.08992756 -0.08750114  0.59512843]
 [-0.0854248  -0.17147849  0.01131717 -0.00060054  0.24618666]
 [-0.15259033  0.39771962 -0.14482404 -0.18161608  0.08131082]
 [ 0.10501318  0.21042793  0.16526926 -0.07439312 -0.40631725]
 [ 0.30442976 -0.22276304 -0.39765592  0.0677928   0.24819641]]


5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [27]:
array = np.random.random((10, 3))
print(array, '\n')
near = array[np.arange(10), np.abs(array - 0.5).argmin(axis=1)]

print(near)


[[0.6491519  0.84691566 0.59681313]
 [0.85104706 0.90826774 0.71019864]
 [0.88657802 0.17800638 0.17302763]
 [0.53228888 0.40595566 0.56440424]
 [0.60165218 0.41583513 0.09372356]
 [0.27551984 0.32503123 0.20055342]
 [0.60601458 0.98234665 0.69766022]
 [0.44096797 0.48336245 0.29427096]
 [0.66125874 0.25978617 0.73025455]
 [0.19495433 0.04219098 0.57726736]] 

[0.59681313 0.71019864 0.17800638 0.53228888 0.41583513 0.32503123
 0.60601458 0.48336245 0.66125874 0.57726736]


6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [30]:
array = np.random.random((6, 6))
print(array, '\n')
result = array.sum(axis=1) / array.max(axis=0)
print(result)


[[0.47492703 0.72718023 0.87997765 0.35829259 0.01189861 0.45724027]
 [0.78176514 0.82721303 0.52601793 0.78939439 0.25498624 0.33296821]
 [0.51137909 0.16982852 0.05268486 0.83027388 0.37008917 0.15798251]
 [0.35412962 0.59693333 0.34205437 0.19458885 0.82436816 0.38393094]
 [0.31107444 0.06535374 0.08123823 0.3490646  0.53325515 0.00833393]
 [0.44207766 0.42454763 0.21221784 0.6448144  0.127371   0.29366081]] 

[3.72172694 4.2459981  2.37760358 3.24712764 1.63558003 4.69050838]


7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [31]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max_element = np.max(x[np.where(x[:-1] == 0)[0] + 1])
print(max_element)

5


8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [39]:
x = np.ones(10)
print(x, '\n')
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x += np.bincount(i, minlength=len(x))
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


Задача со звездочкой.

Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.


In [42]:
from numpy.lib.stride_tricks import sliding_window_view

N = np.random.randint(2, 11)
M = np.random.randint(2, 11)
array = np.random.random((N, M))
window = sliding_window_view(array, (2, 2))
result = window.mean(axis=(-1, -2))
print(array, '\n')
print(result)


[[0.65397874 0.15174328 0.12961333 0.03470847]
 [0.06878272 0.28528244 0.27676746 0.97674284]
 [0.23683565 0.46479802 0.06289146 0.16843575]
 [0.18315976 0.84155034 0.98805449 0.3363122 ]
 [0.6494436  0.06962948 0.11558346 0.53674193]] 

[[0.28994679 0.21085163 0.35445803]
 [0.26392471 0.27243484 0.37120938]
 [0.43158594 0.58932358 0.38892347]
 [0.4359458  0.50370445 0.49417302]]
